FROM openjdk:11.0.9-jdk
MAINTAINER  BribriDnl brieg.dnl@gmail.com
RUN mkdir /usr/local/apps
COPY target/spoon-backend-1.0.0.jar /usr/local/apps
CMD ["java", "-jar", "usr/local/apps/spoon-backend-1.0.0.jar"]



